# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.42.42"
  config.vm.synced_folder "./", "/vagrant", disabled: true
  config.vm.synced_folder "./sf", "/vagrant"

  config.vm.provision "shell", path: "./provision/provision.sh"
end
